-- CreateEnum
CREATE TYPE "UserTheme" AS ENUM ('LIGHT_BUSINESS', 'DARK_ELECTRIC');

-- AlterTable
ALTER TABLE "User" ADD COLUMN "theme" "UserTheme" NOT NULL DEFAULT 'LIGHT_BUSINESS';
ALTER TABLE "User" ADD COLUMN "sessionVersion" INTEGER NOT NULL DEFAULT 0;
